// Vercel build script — runs before the static site is served.
// 1. Reads MAPBOX_TOKEN from environment and writes config.js.
// 2. Minifies + mangles script.js → script.min.js so deployed code is unreadable.
const fs = require('fs');

// ── Load .env file if present (local development only) ────
// Vercel injects env vars directly; locally we parse .env ourselves.
if (fs.existsSync('.env')) {
  fs.readFileSync('.env', 'utf8').split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 1) return;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!(key in process.env)) process.env[key] = val; // env var takes priority
  });
  console.log('[build] .env loaded.');
}

// ── 1. Token ──────────────────────────────────────────────
const token = process.env.MAPBOX_TOKEN || '';

if (!token) {
  console.warn('[build] Warning: MAPBOX_TOKEN env var is not set. Map will not load.');
}

fs.writeFileSync(
  'config.js',
  `// Auto-generated by build.js — do not edit manually.\nwindow.ENV = { MAPBOX_TOKEN: '${token}' };\n`
);
console.log('[build] config.js written.');

// ── 2. Minify script.js → script.min.js ──────────────────
const { minify } = require('terser');
const src = fs.readFileSync('script.js', 'utf8');

minify(src, {
  compress: {
    passes:        2,    // two-pass compression for smaller output
    drop_console:  false,
    pure_getters:  true,
  },
  mangle: {
    toplevel: false, // keep global fn names callable from HTML onclick=""
    reserved: [      // never mangle names called directly from HTML attributes
      'handleGPXUpload','processGPXFile','mapZoom','fitToRoute',
      'setMapStyle','setRouteColor','setRouteWidth','setPosterBg',
      'toggleOption','setMarkerSize','setDashPattern','setDashGap',
      'setTitleFont','setTitleSize','setPosterSize','switchTab',
      'syncText','toggleExportMenu','exportAs','toggleTheme',
      'startEditName','loadFileFromList','deleteFileFromList',
      'toggleTopo','initMap','initElevChart','initDragDrop',
      'mobileTabTap','openSheet','closeSheet','setTitleFont',
      'filterSizes',
    ],
  },
  format: {
    comments: false,  // strip all comments
  },
}).then(result => {
  fs.writeFileSync('script.min.js', result.code);
  const saved = ((1 - result.code.length / src.length) * 100).toFixed(1);
  console.log(`[build] script.min.js written (${saved}% smaller than source).`);
}).catch(err => {
  // Fallback: ship the unminified file rather than breaking the deploy
  console.error('[build] Terser failed — shipping unminified script:', err.message);
  fs.copyFileSync('script.js', 'script.min.js');
});
