// Vercel build script — runs before the static site is served.
// Reads MAPBOX_TOKEN from environment and writes config.js.
const fs = require('fs');

const token = process.env.MAPBOX_TOKEN || '';

if (!token) {
  console.warn('[build] Warning: MAPBOX_TOKEN env var is not set. Map will not load.');
}

fs.writeFileSync(
  'config.js',
  `// Auto-generated by build.js — do not edit manually.\nwindow.ENV = { MAPBOX_TOKEN: '${token}' };\n`
);

console.log('[build] config.js written successfully.');
